#Test error handling of internal errors.
o = Object new.
{\ o on: 2 do: 3.} catch: { e | Pen write: e. }, run.
{\ o on: 'test' do: 3.} catch: { e | Pen write: e. }, run.

