{
	thisBlock error: 'Dont fail.'.
	unknown doSomething.
} catch: {
	✎ write: 'Caught!'.
}, run.

{
	thisBlock error: 'Dont fail.'.
	⚿ unknown doSomething.
} catch: {
	✎ write: 'Caught!'.
}, run.

{
	thisBlock error: 'Dont fail.'.
	unknown := 122.
} catch: {
	✎ write: 'Caught!'.
}, run.


{
	thisBlock error: 'Dont fail.'.
	True break.
	✎ write: 'FAIL'.
} catch: {
	✎ write: 'Caught!'.
}, run.

{
	{
		thisBlock error: 'Dont fail.'.
		True break.
		✎ write: 'FAIL'.
	} catch: { :x
		(x = 'Dont fail.') true: { thisBlock error: 'Nested Caught!'. }.
	}, run.
} catch: { :e
	✎ write: e.
}, run.
